### ISSUE TITLE
Bug with utf chars

### ISSUE THREAD

**Issue by max-mykhailenko** [lingui/js-lingui#902] opened 2020-12-06 19:28 UTC
**Describe the bug**
My compiled messages files contains encoded UTF characters instead of simple utf

<img width="981" alt="image" src="https://user-images.githubusercontent.com/1213198/101289992-6a585600-3808-11eb-8d8e-91f3c7639437.png">

**To Reproduce**
Compile `po` file with Cyrillic characters

**Expected behavior**
Simple not encoded utf chars

- jsLingui version
```
@lingui/cli": "3.2.3",
"@lingui/macro": "3.2.3",
"@lingui/react": "3.2.3",
```
- Babel version ``@babel/core@7.12.9``

**Comment by semoal** [comment] 2020-12-06 19:57
Could you provide a reproduction repo please Max? 
You could use this as base :)
https://codesandbox.io/s/nextjs-lingui-djzqm

**Comment by max-mykhailenko** [comment] 2020-12-06 20:25
@semoal without any changes repo already has this problem. 
<img width="623" alt="image" src="https://user-images.githubusercontent.com/1213198/101291478-c83d6b80-3811-11eb-8cf6-da3a2c093bba.png">

Correct utf char `Jméno` was replaced to `Jm\xE9no`

**Comment by semoal** [comment] 2020-12-07 10:41
I tough this was fixed by babel, i'll take a further look

**Comment by semoal** [comment] 2020-12-07 11:01
Well, I propose my solution, tell me what you think @tricoder42 

1º Create a new configuration param called: `compilerBabelOptions` we already have a `extractBabelOptions`, so for me has sense to difference options of babel by command.
2º Edit https://github.com/lingui/js-lingui/blob/main/packages/cli/src/api/compile.ts#L45 to merge our defaut configuration of the generator with `compileBabelOptions`, basically this will allow to BABEL 7 users to modify `.linguirc` to accept https://github.com/mathiasbynens/jsesc#minimal:

```json
{
 "locales": ["en", "ru"],
 "compilerBabelOptions": {
	"generatorOpts": {
		"jsescOption": {
			"minimal": true
		}
	}
  }
}
```

Also I think that is not a big problem of having ASCII codes in compiled catalogs, because if your html contains in the <html charset="utf8"> problems are gone... 

@max-mykhailenko As you can see .po file the accent is working properly and also in the view, so probably this fix will try to fix something that is negligible

**Comment by max-mykhailenko** [comment] 2020-12-07 12:32
@semoal for me it's not something negligible because it increases total file size in five times.

**Comment by semoal** [comment] 2020-12-07 13:13
<img width="1357" alt="Screenshot 2020-12-07 at 14 13 01" src="https://user-images.githubusercontent.com/22656541/101355049-565b3580-3896-11eb-9732-6e562ca06480.png">
I already got this fixed, I'll create a merge request asap

**Comment by tricoder42** [comment] 2020-12-07 18:28
As I wrote in #906, since we don't support Babel 6, what about making it the default behavior? This could definitely save lot of space as @max-mykhailenko pointed out

**Comment by semoal** [comment] 2020-12-07 18:36
Has sense to me, we can set this to default yes

I'll update the pr later im out home right now

**Comment by tricoder42** [comment] 2020-12-07 18:39
Thank you @semoal. If we make it default we should definitely mention it in changelog. If it changes msgids for someone, it might break translations (well, break. Those translations will be empty until they move translations from previous msgids)

**Comment by semoal** [comment] 2020-12-08 12:17
Yes once released we just have to edit the changelog with any addtioanl comments .

**Closed** 2020-12-08 13:26 UTC
Labels: 🐞bug, 📦 cli

**Comment by max-mykhailenko** [comment] 2020-12-09 09:40
@semoal @tricoder42 thank you guys, awesome work!
