### ISSUE TITLE
Using Trans inside a Plural macro unexpectedly replaces "#" found in variables

### ISSUE THREAD

**Issue by kiejo** [lingui/js-lingui#1826] opened 2024-01-03 15:02 UTC
**Describe the bug**
Using `Trans` with the `Plural` macro can lead to variables being rendered in a modified way. It should be possible for a variable to contain "#" without it being replaced with the `value` of the `Plural` macro.

**To Reproduce**
Define a component, which uses a nested `Trans` within the `Plural` macro:
```jsx
import {Plural, Trans} from '@lingui/macro'

function Notification({count, documentTitle}) {
  return (
    <p>
      <Plural
        value={count}
        one={<Trans>There is a notification in <span>{documentTitle}</span></Trans>}
        other={<Trans>There are # notifications in <span>{documentTitle}</span></Trans>}
      />
    </p>
  )
}
```

**Expected behavior**
Rendering the component using this code:
```jsx
<Notification
  count={1}
  documentTitle="Title #1"
/>
```
Should result in
```html
<p>There is a notification in <span>Title #1</span></p>`
```
but it generates
```html
<p>There is a notification in <span>Title 11</span></p>
``` 
As you can see, the "#" found in the `documentTitle` variable is replaced with the count "1". It renders as `Title 11` instead of `Title #1`.

I think the expected behavior is to leave variables untouched and render them as is. Only hashtags that are directly part of the translation string should be replaced.

**Additional context**

- jsLingui version `4.6.0`
- Babel version `7.23.3`
- I'm using Babel with `babel-macro-plugin`

**Comment by jozefmery** [comment] 2024-02-13 17:28
Hi, I investigated this issue and I believe the core of the issue is that the interpolation [here](https://github.com/lingui/js-lingui/blob/685730feefbd0eec12beb6e68f786ad3f73e28d4/packages/core/src/interpolate.ts#L91) runs before the [replaceOctothorpe](https://github.com/lingui/js-lingui/blob/685730feefbd0eec12beb6e68f786ad3f73e28d4/packages/core/src/interpolate.ts#L20) function that uses the `String#replace` method. By interpolating first, there is no easy way of knowing where the `#` originated from in the component hierarchy. Furthermore, by using the `String#replace` method, only the first occurence is replaced as the provided # pattern [here](https://github.com/lingui/js-lingui/blob/685730feefbd0eec12beb6e68f786ad3f73e28d4/packages/core/src/interpolate.ts#L25) is a string. Currently, there is no escape hatch for the replacement of the # symbol that I know of.

To solve this issue I propose the following: **Remove the # related behavior entirely**

I believe that a better and simpler solution to include the actual number in a plural sentence is to use the well-established templating approach of Lingui (e.g.: `There are ${count} apples`). `replaceOctothorpe` additionally formats the number for you (`number style` by default), but you may do that as you would anywhere else: `There are ${i18n.number(count, ...)} apples`.  This approach covers more (albeit edge-case) use-case as it allows you to include the number any times, and eliminates the issues related to a bespoke templating systems that sort of goes against the philosophy of the library.

I would love to hear your feedback and please let me know if I missed anything.

**Comment by thekip** [comment] 2024-02-13 17:32
Thanks for digging into the issue, the "octothorpe" symbol is part of ICU messages spec, so that's why there are here.

**Comment by jozefmery** [comment] 2024-02-13 18:48
Thank you for the rapid response. You are correct I did not consider that, so the replacing of the # is correct, except I believe every instance should be replaced. Furthmore, literal # and any other special symbols are supported by enclosing them in single quotes `'#'` and a single quote is represented by two consecutive ones `''`. It is described [here](https://unicode-org.github.io/icu/userguide/format_parse/messages/#quotingescaping). You can check out this [online editor](https://format-message.github.io/icu-message-format-for-translators/editor.html?m=%7B%20gender%2C%20select%2C%0A%C2%A0%C2%A0other%20%7B%7B%0A%C2%A0%C2%A0%C2%A0%20count%2C%20plural%2C%0A%C2%A0%C2%A0%C2%A0%C2%A0other%20%7B%27%23%27%23%7D%0A%C2%A0%C2%A0%7D%7D%0A%7D).

**Comment by thekip** [comment] 2024-02-14 15:14
will be fixed by https://github.com/lingui/js-lingui/pull/1850

**Closed** 2024-02-15 07:52 UTC
Labels: bug, help wanted
