### ISSUE TITLE
`Maximum call stack size exceeded` when run against large number of files

### ISSUE THREAD

**Issue by taozhou-glean** [lingui/js-lingui#1428] opened 2023-02-11 00:18 UTC
**Describe the bug**

Quite similar to https://github.com/lingui/js-lingui/issues/1405, but the issue still exists (with different error) after switching to js config file.

We have hundreds of files within the codebase, I am just converting 2 files with macros, and when I ran `yarn extract files`, it works just fine, but if no `files` passed and let it run against the whole code base, I hit the following error every time, and only on those two files.

The error stack:

```
✖ /Users/xx/SomeComponentFile.tsx: Maximum call stack size exceeded    ....
    at require.extensions.<computed> (/Users/xx/node_modules/ts-node/src/index.ts:1607:29)
    at require.extensions.<computed> (/Users/xx/node_modules/ts-node/src/index.ts:1608:43) {
  code: 'BABEL_TRANSFORM_ERROR'
}
```

lingui.config.js

```
module.exports = {
  catalogs: [
    {
      exclude: [
        '**/node_modules/**',
      ],
      include: [
        'src'
      ],
      path: 'locales/{locale}/messages',
    },
  ],
  compileNamespace: 'cjs',
  extractors: [require.resolve('@lingui/cli/api/extractors/typescript')],

  fallbackLocales: {
    default: 'en',
  },

  format: 'po',

  locales: ['en', 'pseudolocalization'],

  orderBy: 'messageId',

  pseudoLocale: 'pseudolocalization',
  sourceLocale: 'en',
}
```

I tried to add a new file with the minimum Trans, and it also failed:

```
import { Trans } from '@lingui/macro'

function A() {
 return <Trans id="test">test text</Trans>
}
```

It's a bit hard to get a minimum repro case since as soon as I narrow the `include` above to a smaller set including those 2 files, the issue will be gone.

I tried to debug locally but did not get too far, it looks like the failure happens within the `transform`, and [at the traverse](https://github.com/babel/babel/blob/1b794363afa277be50d8b2a27d140368b347df33/packages/babel-core/src/transformation/index.ts#L119), even before running against any of the plugin... but exact same file will pass if just pass the file or smaller set of the files... 

- jsLingui version : `v3.17.1`
- Babel version `@babel/core@7.20.12`
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)
no

**Comment by taozhou-glean** [comment] 2023-02-11 00:20
well looks like it is babel/core issue, after pinning it down to `v7.0.0` as used in `@lingui/cli`, it passed without any issue

**Comment by taozhou-glean** [comment] 2023-02-11 00:25
will x-post to babel if I can narrow it down to a minimum repro case, seems this happened quite often there in the past: https://github.com/babel/babel/issues?q=Maximum+call+stack+size+exceeded

I guess in the meantime, the workaround will be just pin the babel/core version to v7.0.0

**Comment by thekip** [comment] 2023-02-11 12:54
`ts-node` should not be involved in the extraction process. As long you use  `js` fextension for config and not a `ts`. 

Look for the issue in your own code. 

Also i recommend omitting this one: 
```ts
  extractors: [require.resolve('@lingui/cli/api/extractors/typescript')],
```

**Comment by thekip** [comment] 2023-02-15 10:57
@taozhou-glean have you managed to find a root cause of issue?

**Comment by taozhou-glean** [comment] 2023-02-15 16:46
unfortunately no, I observe same error after switching to the babel extractor, not sure why `ts-node` was involved here.

but as I mentioned, it works just fine when we pass files explicitly, so for now I am just using `--watch` mode, which makes it a bit hard to clean up the obsolette messages tho

**Comment by thekip** [comment] 2023-02-15 20:54
Could you try the latest changes from `next` branch? i'm trying to understand have issue solved or we need to dig deeper

**Comment by taozhou-glean** [comment] 2023-02-15 21:45
interesting, so after I cleaned all the caches and re-installed all the packages, still the latest master, now the error went away with the babel extractor, I think we can close this one, I can re-open if it happened again in the future. Thanks for the help!

**Comment by taozhou-glean** [comment] 2023-02-16 01:23
well it came back, so if I am running some codemod to do the transform, and if I run it on the entire codebase (~600 files modified), and then `extract` works just fine, but if I just modify a few files, then run the `extract`, it always crash...  but it works again if I just pass those files to extract... same for `next`

**Comment by thekip** [comment] 2023-02-16 08:20
Try to remove these lines https://github.com/lingui/js-lingui/blob/next/packages/conf/src/getConfig.ts#L47-L49 then recompile and test in your project.

**Comment by taozhou-glean** [comment] 2023-02-16 17:40
actually I had a mistake when link the next version, I don't need to remove those lines, the next version works like a charm! tried one file and a few files and all files, all worked well!

Do we know what is the root cause here and is it possible to port it back to main ? thanks! @thekip

**Comment by thekip** [comment] 2023-02-16 17:47
Glad to hear that code from next branch doesn't have this issue. 
We have codefreeze on the v3 version, so we are not planning to backport any changes. But don't worry, biggest part of v4 is already done.  So I'm expecting release soon.

**Comment by taozhou-glean** [comment] 2023-02-16 18:15
that's awesome to hear! can not wait ;)

**Comment by thekip** [comment] 2023-02-19 09:49
I think we can close that, as it already fixed in v4.

**Closed by thekip** 2023-02-19 09:49 UTC
