### ISSUE TITLE
[next] Unknown option "formatOptions" even with "lingui" format

### ISSUE THREAD

**Issue by dominikdosoudil** [lingui/js-lingui#690] opened 2020-05-13 11:18 UTC
**Describe the bug**
While extracting messages, `cli` gives output:
```
● Validation Warning:

  Unknown option "formatOptions" with value {"origins": false} was found.
  This is probably a typing mistake. Fixing it will remove this message.
```
However by the *new* docs: https://js-lingui-git-next.lingui-js.now.sh/ref/conf.html#formatoptions
it should be possible to configure it this way.

**To Reproduce**
(listing only lingui deps so it's clear what version I am using, ofc `react` etc. is needed as well but I believe that this error occurs even before any react file is loaded anyway)
in `package.json` add
```
  "devDependencies": {
    "@lingui/cli": "^3.0.0-11",
    "@lingui/macro": "^3.0.0-11"
  }
  "dependencies": {
    "@lingui/react": "^3.0.0-11"
  }
  "lingui": {
    "catalogs": [{
      "path": "<rootDir>/locale/{locale}/messages",
      "include": ["<rootDir>/src"],
      "exclude": ["**/node_modules/**"]
    }],
    "compileNamespace": "es",
    "extractBabelOptions": {},
    "fallbackLocale": "",
    "format": "lingui",
    "formatOptions": {
      "origins": false
    },
    "locales": ["cs", "en"],
    "orderBy": "messageId",
    "pseudoLocale": "",
    "rootDir": ".",
    "runtimeConfigModule": ["@lingui/core", "i18n"],
    "sourceLocale": "en"
  }
```

```
import { Trans } from "@lingui/react"

export default function App() {
   return <Trans id="This should be extracted" />
}
```

**Expected behavior**
It shall extract 

**Additional context**

- jsLingui version: *3.0.0-11*
- Babel version: *@babel/core@7.9.6 *
- .babelrc
```
{
  "presets": ["@babel/preset-env", "@babel/preset-react", "@babel/preset-typescript"],
  "plugins": ["macros"]
}
```

**Comment by tricoder42** [comment] 2020-05-25 04:38
Thanks! This seems to be duplicate of #634 which is already fixed in #661

**Closed by tricoder42** 2020-05-25 04:38 UTC
