### ISSUE TITLE
Cannot find module 'ts-node'

### ISSUE THREAD

**Issue by niksauer** [lingui/js-lingui#1401] opened 2023-02-03 17:23 UTC
**Describe the bug**
```
$ lingui compile
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module 'ts-node'
Require stack:
- /Users/nik/Developer/flexibits/flexibits-web-frontend/node_modules/@lingui/conf/node_modules/cosmiconfig-typescript-loader/dist/cjs/index.js
- /Users/nik/Developer/flexibits/flexibits-web-frontend/node_modules/@lingui/conf/build/index.js
- /Users/nik/Developer/flexibits/flexibits-web-frontend/node_modules/@lingui/cli/build/lingui-compile.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/nik/Developer/flexibits/flexibits-web-frontend/node_modules/@lingui/conf/node_modules/cosmiconfig-typescript-loader/dist/cjs/index.js:28:22)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/nik/Developer/flexibits/flexibits-web-frontend/node_modules/@lingui/conf/node_modules/cosmiconfig-typescript-loader/dist/cjs/index.js',
    '/Users/nik/Developer/flexibits/flexibits-web-frontend/node_modules/@lingui/conf/build/index.js',
    '/Users/nik/Developer/flexibits/flexibits-web-frontend/node_modules/@lingui/cli/build/lingui-compile.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**
```
{
  "dependencies": {
    [...]
    "@lingui/react": "^3.17.0",
    "react-scripts": "5.0.1",
  },
  "scripts": {
    [...]
    "task:trans-extract": "lingui extract --clean",
    "task:trans-compile": "lingui compile"
  },
  "devDependencies": {
    [...],
    "@lingui/cli": "^3.17.0",
    "@lingui/macro": "^3.17.0",
    "typescript": "4.5.5"
  },
}
```

**Comment by thekip** [comment] 2023-02-03 17:29
What format do you use for your linguirc config file?

**Comment by ryanb** [comment] 2023-02-03 17:49
@thekip I'm getting this error as well. I don't have a linguirc file but I have a `lingui.config.js` file.

**Comment by xchwarze** [comment] 2023-02-03 21:13
The same thing has been happening to me since yesterday.
I tried to force the version of lingui to the one I had originally installed but for some reason it keeps throwing this error.

**Comment by adamsoderstrom** [comment] 2023-02-05 18:57
Running into this error as well.
It is my first time setting it up, though.
Compared to @ryanb, i'm using a `.linguirc` file.

**Comment by thekip** [comment] 2023-02-06 08:28
Would be fixed by this: https://github.com/lingui/js-lingui/pull/1403

**Closed** 2023-02-06 10:14 UTC
Labels: bug, help wanted

**Comment by renchap** [comment] 2023-02-23 17:45
I am still hitting this issue with the latest 3.17.1 version, using Vite:

```
vite     |   VITE v3.2.5  ready in 1519 ms
vite     |
vite     |   ➜  Local:   http://127.0.0.1:3036/vite-dev/
vite     | ✘ [ERROR] Could not resolve "ts-node"
vite     |
vite     |     ../../node_modules/cosmiconfig-typescript-loader/dist/cjs/index.js:28:29:
vite     |       28 │ var import_ts_node = require("ts-node");
vite     |          ╵                              ~~~~~~~~~
vite     |
vite     |   You can mark the path "ts-node" as external to exclude it from the bundle, which will remove this
vite     |   error. You can also surround this "require" call with a try/catch block to handle this failure at
vite     |   run-time instead of bundle-time.
vite     |
vite     | /Users/renchap/dev/notos/node_modules/vite/node_modules/esbuild/lib/main.js:1575
vite     |   let error = new Error(`${text}${summary}`);
vite     |               ^
vite     |
vite     | Error: Build failed with 1 error:
vite     | ../../node_modules/cosmiconfig-typescript-loader/dist/cjs/index.js:28:29: ERROR: Could not resolve "ts-node"
vite     |     at failureErrorWithLog (/Users/renchap/dev/notos/node_modules/vite/node_modules/esbuild/lib/main.js:1575:15)
vite     |     at /Users/renchap/dev/notos/node_modules/vite/node_modules/esbuild/lib/main.js:1033:28
vite     |     at runOnEndCallbacks (/Users/renchap/dev/notos/node_modules/vite/node_modules/esbuild/lib/main.js:1447:61)
vite     |     at buildResponseToResult (/Users/renchap/dev/notos/node_modules/vite/node_modules/esbuild/lib/main.js:1031:7)
vite     |     at /Users/renchap/dev/notos/node_modules/vite/node_modules/esbuild/lib/main.js:1143:14
vite     |     at responseCallbacks.<computed> (/Users/renchap/dev/notos/node_modules/vite/node_modules/esbuild/lib/main.js:680:9)
vite     |     at handleIncomingPacket (/Users/renchap/dev/notos/node_modules/vite/node_modules/esbuild/lib/main.js:735:9)
vite     |     at Socket.readFromStdout (/Users/renchap/dev/notos/node_modules/vite/node_modules/esbuild/lib/main.js:656:7)
vite     |     at Socket.emit (node:events:527:28)
vite     |     at addChunk (node:internal/streams/readable:315:12) {
vite     |   errors: [
vite     |     {
vite     |       detail: undefined,
vite     |       id: '',
vite     |       location: {
vite     |         column: 29,
vite     |         file: '../../node_modules/cosmiconfig-typescript-loader/dist/cjs/index.js',
vite     |         length: 9,
vite     |         line: 28,
vite     |         lineText: 'var import_ts_node = require("ts-node");',
vite     |         namespace: '',
vite     |         suggestion: ''
vite     |       },
vite     |       notes: [
vite     |         {
vite     |           location: null,
vite     |           text: 'You can mark the path "ts-node" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.'
vite     |         }
vite     |       ],
vite     |       pluginName: '',
vite     |       text: 'Could not resolve "ts-node"'
vite     |     }
vite     |   ],
vite     |   warnings: []
vite     | }
vite     | Exited
```

Is this expected?

**Comment by thekip** [comment] 2023-02-23 17:53
No, and it's strange that vite is trying to bundle it. Are you sure you are not importing a macro without the corresponding babel/swc plugin?

**Comment by renchap** [comment] 2023-02-23 18:06
I am using `@lingui/vite-plugin` in my vite config, `babel-plugin-macros` in my `@vitejs/plugin-react` babel plugins config, and not using SWC, so I dont think so?

**Comment by thekip** [comment] 2023-02-23 18:16
could you create a minimal repo, i will take a look

**Comment by thekip** [comment] 2023-02-24 08:48
I reproduced it by myself.

**Comment by thekip** [comment] 2023-02-24 08:52
https://github.com/lingui/js-lingui/issues/1464
