### ISSUE TITLE
SyntaxError: "export declarations may only appear at top level of a module"

### ISSUE THREAD

**Issue by pauldariye** [lingui/js-lingui#555] opened 2019-08-20 07:08 UTC
**Describe the bug**

I am able to `extract` and `compile` without any problems, however using the `@lingui/loader` to load catalogs isn't working. 

I've tried using the dynamic loader like so:

```
            const catalog = await import(
                /* webpackMode: "lazy", webpackChunkName: "i18n-[index]" */
                `@lingui/loader!locales/${language}/messages.po`
            )
```

And the static loader

```
            const catalog = await import(
                /* webpackMode: "lazy", webpackChunkName: "i18n-[index]" */
                `locales/${language}/messages.js`
            )

```

Here's a screenshot of the error I get

![Screenshot 2019-08-20 at 08 59 53](https://user-images.githubusercontent.com/3650761/63325187-eedc4800-c329-11e9-9f65-be53e030f15e.png)

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, I'm using the example loader component

```
import {I18nProvider} from '@lingui/react'
import React, {ReactNode} from 'react'
import {connect} from 'react-redux'
import {getLanguage} from 'store/locale/selectors'

interface OwnProps {
    children: ReactNode
}

interface ConnectedProps {
    language: string
}

export type Props = OwnProps & ConnectedProps

interface State {
    catalogs: any
}

class I18nLoader extends React.Component<Props, State> {
    state = {
        catalogs: {}
    }

    componentDidMount() {
        this.loadCatalog(this.props.language)
    }

    shouldComponentUpdate(nextProps, nextState) {
        const {language} = nextProps
        const {catalogs} = nextState

        if (language !== this.props.language && !catalogs[language]) {
            this.loadCatalog(language)
            return false
        }

        return true
    }

    loadCatalog = async (language) => {
        try {
            const catalog = await import(
                /* webpackMode: "lazy", webpackChunkName: "i18n-[index]" */
                `@lingui/loader!locales/${language}/messages.po`
            )

            this.setState((state) => ({
                catalogs: {
                    ...state.catalogs,
                    [language]: catalog
                }
            }))
        } catch (err) {
            console.log(err)
        }
    }

    render() {
        const {children, language} = this.props
        const {catalogs} = this.state

        if (!catalogs[language]) {
            return null
        }

        return <I18nProvider language={this.props.language}>{children}</I18nProvider>
    }
}

export default connect(
    (state) => ({
        language: getLanguage(state)
    }),
    null
)(I18nLoader)

```

Using it like so in my entry file:

```
ReactDom.render(
    <ErrorBoundary>
        <Provider store={store}>
			<I18nLoader>
            	<Router history={history} routes={getRoutes(store)} />
            </I18nLoader>
        </Provider>
    </ErrorBoundary>,
    document.getElementById('app')
)

```

**Expected behavior**
I expect the app to load with the default `locale`:`en` set in the redux store.

**Additional context**

- jsLingui version ``lingui --version``: `2.8.3`
- Babel version ``npm list babel-core``: `7.5.5`
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)

`.babelrc`:

```
{
    "presets": [
        "@babel/preset-env",
        "@babel/react",
        "@babel/typescript",
        "@lingui/babel-preset-react"
    ],
    "plugins": [
        "macros",
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-proposal-object-rest-spread",
        "syntax-dynamic-import",
        "transform-class-properties"
    ],
    "env": {
        "test": {
            "plugins": ["dynamic-import-node"]
        }
    }
}

```

`tsconfig.json`:

```
{
    "compilerOptions": {
        "allowJs": true,
        "allowSyntheticDefaultImports": true,
        "baseUrl": "./app/scripts/",
        "checkJs": false,
        "jsx": "react",
        "lib": ["es2016", "dom"],
        "module": "commonjs",
        "esModuleInterop": true,
        "moduleResolution": "node",
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "outDir": "./build",
        "paths": {
            "*": ["*.web", "*"],
            "config": ["../config/config.js"],
            "test/*": ["../../test/*"],
            "types/*": ["../types/*"]
        },
        "target": "es2016",
        "strictNullChecks": true,
        "sourceMap": true,
        // Workaround jest + mocha + cypress types conflict https://github.com/cypress-io/cypress/issues/1087
        "skipLibCheck": true
    },
    "include": ["./app/types/globals.d.ts", "./app/types/imports.d.ts", "./app/**/*"]
}

```

`.linguirc`:

```
{
   "localeDir": "app/locales/",
   "srcPathDirs": ["app/"],
   "format": "po",
    "compileNamespace": "es",
    "sourceLocale": "en"
}
```

**Comment by meldafert** [comment] 2020-04-07 17:41
The problem seems to be the `"compileNamespace": "es"` option in `.linguirc`.
This outputs the compiles lang files as esmodules (with top-level export), which are then fed into webpack as if they were cjs.

To fix this, just use `"compileNamespace": "cjs"` or remove the option as `"cjs"` is the default.

This option appears to be ignored in lingui-loader versions before 2.8.0, but now it is expected behaviour.

This is a duplicate of #609.

**Closed** 2020-04-07 17:42 UTC
