### ISSUE TITLE
lingui extract and compile fail the CI build when changes not committed

### ISSUE THREAD

**Issue by vkodimut** [lingui/js-lingui#629] opened 2020-04-08 16:29 UTC
I am trying to find a way when developer make changes to UI component but forget to run `lingui extract` and `lingui compile` and commit the changes to `/messages.json`. 
As part of CI build when I run `extract` and `compile` commands I would like the build fail due to changes not being part of branch/PR.
I have tried `lingui compile --strict` option but no luck.

Could you please suggest anything I can try.

**Comment by tricoder42** [comment] 2020-10-17 07:49
Duplicate of #724

**Closed by tricoder42** 2020-10-17 07:49 UTC
