### ISSUE TITLE
Unintentionally component is transformed when the same naming as the macro component

### ISSUE THREAD

**Issue by erm1116** [lingui/js-lingui#2080] opened 2024-11-06 07:06 UTC
**Describe the bug**
In the `Trans` component children, components named `Select`/`SelectOrdinal`/`Plural` that are not from @lingui/macro are unintentionally transformed.

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```tsx
import { Trans } from "@lingui/macro"
import { Select, SelectOrdinal, Plural } from "other-package"

export default function App() {
	return (
		<Trans>
			This should be translated!
			{/* The following components are transformed by babel even though they are not components of @lingui/macro */}
			<Select prop="this should not be replaced" />
			<SelectOrdinal prop="this should not be replaced" />
			<Plural prop="this should not be replaced" />
		</Trans>
	)
}
```

**Expected behavior**
expected output is like below
```tsx
import { Trans } from "@lingui/react"
import { Select, SelectOrdinal, Plural } from "other-package"

export default function App() {
	return (
		<Trans 
			id={"<id>"}
			message="This should be translated!<0/><1/><2/>"
			components={{
				0: <Select prop="this should not be replaced" />
				1: <SelectOrdinal prop="this should not be replaced" />
				2: <Plural prop="this should not be replaced" />
			}}
		/>
	)
}
```

**Additional context**

- jsLingui version `4.11.4`
- Babel version `7.25.2`
- Macro support:
 - [ ] I'm using SWC with `@lingui/swc-plugin` (As far as I checked swc-plugin implementation, it checks import_id_map so I don't think the problem occurs)
 - [x] I'm using Babel with `babel-macro-plugin`
 - [ ] I'm not using macro
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, NextJs, Vite)

**Comment by andrii-bodnar** [comment] 2024-11-06 13:51
@timofei-iatsenko I will be releasing a new 4.x version. Just wondering, should I wait for some fix related to this issue to be included in that release or not?

**Comment by timofei-iatsenko** [comment] 2024-11-06 15:46
@andrii-bodnar no, i will do the fix for V5

**Comment by timofei-iatsenko** [comment] 2024-11-06 15:54
@erm1116 just checked, it's already fixed in V5. I could not reproduce the issue there.

**Closed** 2024-11-06 15:54 UTC
