### ISSUE TITLE
Improve error message when plurals aren't loaded

### ISSUE THREAD

**Issue by ImADrafter** [lingui/js-lingui#798] opened 2020-10-30 13:31 UTC
## Tasks

- [x] show `console.error` "Plurals for locale {locale} aren't loaded. Use i18n.loadLocaleData method to load plurals for specific locale. Using `other` plural rule as a fallback."
- [x] Use `other` plural rule as a fallback

I know this isn't 100% accurate, because some locales, e.g. pl, ru, actually use `many` as a fallback rule, while `other` is used fo decimal numbers. However, this shouldn't be used in production anyway. It's just for easier debugging.

---

Original post:

**Describe the bug**
Using plurals, when an unsupported language gets activated (via i18n.activate) which was not loaded via `loadLocaleData`, app breaks.
![image](https://user-images.githubusercontent.com/44379989/97709990-750e2580-1abb-11eb-8676-ed2252fc95c5.png)

Without using plurals, just a console warn pops out:
![image](https://user-images.githubusercontent.com/44379989/97709924-60319200-1abb-11eb-8dd8-65bc6ae7cd8f.png)

An example of how this could happen, is when you activate users browser language, which potentially is not under the loaded plurals. 

**To Reproduce**
[CodeSandBox](https://codesandbox.io/s/dreamy-haze-5p5y9?file=/src/App.tsx)

**Expected behavior**
We expected the same behaviour as working without plurals. Plurals will be computed with fallback language or loaded plurals.

**Additional context**
Even when the issue is not the same (I already have some plurals loaded) this could be a related one: https://github.com/lingui/js-lingui/issues/437

- jsLingui version ``3.0.0``
- Create React App (3.3.0)

**Comment by tricoder42** [comment] 2020-10-30 14:01
> Plurals will be computed with fallback language or loaded plurals.

Using fallback locale would be an option, but using loaded plurals from other locale seems weird. In both cases you'll end up with terrible UX, although it might be better than blank screen.

Why can't you fix the root cause and load the plurals *before* calling `i18n.activate`?

**Comment by tricoder42** [comment] 2020-10-30 14:03
I think we could improve DX here and show better error message, e.g. `plurals not loaded, call i18n.loadLocaleData`, but I believe it's better to fix the app, rather that let the library display wrong messages

**Comment by ImADrafter** [comment] 2020-10-30 14:21
Thank you @tricoder42 for your quick response!

> > Plurals will be computed with fallback language or loaded plurals.
> 
> Using fallback locale would be an option, but using loaded plurals from other locale seems weird. In both cases you'll end up with terrible UX, although it might be better than blank screen.
> 
> Why can't you fix the root cause and load the plurals _before_ calling `i18n.activate`?

Hmm you mean make a dynamic import of the user language before activating ? Or should I call loadLocaleData with every possible locale ? Like preventing i18n to activate with an unsupported language.

**Comment by tricoder42** [comment] 2020-10-30 14:25
> call loadLocaleData with every possible locale

I would start with this. Plurals are usually very small, just one function.

> Hmm you mean make a dynamic import of the user language before activating ?

When you hit size issues, I would start loading locale data before activating. Check the `next-js`  example, it load message catalogs on demand, but locale data are bundled in the app.

**Comment by tricoder42** [comment] 2020-10-31 08:55
Hey @ImADrafter, I believe we could improve error message to ease troubleshooting. I've added proposal for possible fix at the top of your OP. Feel free to send a PR if you have free time.

**Comment by miguelCT** [comment] 2020-11-04 09:31
The question that comes to mind is, why do i have to load the plurals for **every language** if i'm officially only supporting a few of them? 

For example, in my app I only support **'es' and 'en'**, so I loaded only these plurals. But I also use the language detector, so when a user from **'pl'** comes to the app, it could (at least) format dates and numbers to the 'pl' format, even though the app does not support the 'pl' translation. (in this case, the app will use the fallback locale). 

What I expected with Plurals is the same logic as with the translations, that is to say that those Plurals would use the same fallback as the language locale, so that the user with a non-supported language can still use the app with the fallback Plurals, instead of getting that blank page that breaks the whole app.

I understand that I can straight away load every Plural, as they are small functions, but still, why should I bloat my app with things that possibly will never be used?

**Comment by tricoder42** [comment] 2020-11-04 10:32
> For example, in my app I only support 'es' and 'en', so I loaded only these plurals. But I also use the language detector, so when a user from 'pl' comes to the app, it could (at least) format dates and numbers to the 'pl' format, even though the app does not support the 'pl' translation. (in this case, the app will use the fallback locale).

Unfortunately this isn't possible at the moment. You could instruct your locale detector to use `en` as a fallback locale (and it'll use `en` plurals), but then all dates and numbers will be in `en` as well. There's no way to tell the library to use `en` for messages, but `pl` for formatting.

That said, you don't need to load plurals for *every language*. Only for those locales you support.

**Closed** 2020-11-05 13:30 UTC
Labels: triage: accepted, 💡new feature, 📦  core
