### ISSUE TITLE
Why do I need to install @babel/core ? Isn't that already installed when using create react app ?

### ISSUE THREAD

**Issue by ahmedosama5200** [lingui/js-lingui#735] opened 2020-09-14 12:29 UTC
In the documentation [here](https://lingui.js.org/tutorials/setup-react.html), It says you need to install @babel/core and @babel-core@bridge even when using create-react-app. Isn't it already installed ?

**Comment by tricoder42** [comment] 2020-10-10 14:13
Duplicate of #748

**Closed by tricoder42** 2020-10-10 14:13 UTC
