### ISSUE TITLE
Babel throws "Plugin/Preset files are not allowed to export objects, only functions."

### ISSUE THREAD

**Issue by ktunkiewicz** [lingui/js-lingui#171] opened 2018-02-26 23:37 UTC
lingui 2.0.4, babel 7.0.0-beta.40

```
> lingui extract --clean

Extracting messages from source files…
/code/App/node_modules/@babel/core/lib/config/config-descriptors.js:158
    throw new Error("Plugin/Preset files are not allowed to export objects, only functions.");
    ^

Error: Plugin/Preset files are not allowed to export objects, only functions.
    at createDescriptor (/code/App/node_modules/@babel/core/lib/config/config-descriptors.js:158:11)
    at /code/App/node_modules/@babel/core/lib/config/config-descriptors.js:101:12
    at Array.map (<anonymous>)
    at createDescriptors (/code/App/node_modules/@babel/core/lib/config/config-descriptors.js:100:27)
    at createPresetDescriptors (/code/App/node_modules/@babel/core/lib/config/config-descriptors.js:92:10)
    at /code/App/node_modules/@babel/core/lib/config/config-descriptors.js:64:19
    at presets (/code/App/node_modules/@babel/core/lib/config/config-descriptors.js:54:25)
    at mergeChainOpts (/code/App/node_modules/@babel/core/lib/config/config-chain.js:294:68)
    at /code/App/node_modules/@babel/core/lib/config/config-chain.js:247:7
    at buildRootChain (/code/App/node_modules/@babel/core/lib/config/config-chain.js:83:20)
```

There's a closed issue mentioning something like this: https://github.com/lingui/js-lingui/issues/163

The difference is that I actually *updated to 2.0.4 from 2.0.0 and got this error* (while the author of issue#163 had an opposite situation - he was getting this on 2.0.2 and it was "fixed" and updated to 2.0.4)

Any ideas how to fix that?

**Comment by tricoder42** [comment] 2018-02-27 09:17
What's the output of `npm list | grep lingui` command?

As a workaround, could you replace the preset with plugins and try that?

**Comment by ktunkiewicz** [comment] 2018-02-28 10:25
```
❯❯❯ npm list | grep lingui
├─┬ @lingui/babel-preset-react@2.0.4
│ ├── @lingui/babel-plugin-transform-js@2.0.4
│ └── @lingui/babel-plugin-transform-react@2.0.4
├─┬ @lingui/cli@2.0.4
│ ├─┬ @lingui/babel-plugin-extract-messages@2.0.4
│ │ └── @lingui/conf@2.0.4 deduped
│ ├── @lingui/babel-plugin-transform-js@2.0.4 deduped
│ ├── @lingui/babel-plugin-transform-react@2.0.4 deduped
│ ├─┬ @lingui/conf@2.0.4
├─┬ @lingui/loader@2.0.4
│ ├── @lingui/cli@2.0.4 deduped
│ ├── @lingui/conf@2.0.4 deduped
├─┬ @lingui/react@2.0.4
│ ├─┬ @lingui/core@2.0.4
```

@tricoder42 not sure if you noticed that this happens when I run `lingui extract --clean`. How can I "replace the preset with plugins" in it?

**Comment by ktunkiewicz** [comment] 2018-02-28 11:43
I also checked version 2.0.2 and it works fine, no errors, only when I switch to 2.0.4.

**Comment by tricoder42** [comment] 2018-03-02 07:11
Could you please show me your `.babelrc`? Running `lingui extract` inside one of examples works fine. It's weird it worked in 2.0.2 and doesn't work now though.

**Comment by tricoder42** [comment] 2018-03-02 07:19
I was having the same problem on one of my projects which was still using Babel 6. I updated it to Babel 7 and now `lingui extract` works fine. Here's my `.babelrc`:

```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "browser": [
            ">1%",
            "last 4 versions",
            "Firefox ESR",
            "not ie < 9",
            "ie 11"
          ],
          "uglify": true
        },
        "modules": false
      }
    ],
    "@babel/preset-react",
    "@babel/preset-flow",
    "@lingui/babel-preset-react"
  ],
  "plugins": [
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-object-rest-spread",
    "@babel/plugin-proposal-decorators"
  ],
  "env": {
    "test": {
      "plugins": [
        "@babel/plugin-transform-modules-commonjs"
      ]
    }
  }
}
```

... but the [.babelrc](https://github.com/lingui/js-lingui/blob/master/examples/webpack-react/.babelrc) in example works fine as well.

Please let me know, I'm curious what's happening.

**Comment by bs1180** [comment] 2018-03-03 19:32
I'm having this same issue trying to use Lingui with next.js. My .babelrc consists of:

```
{
  "presets": [
    "next/babel",
    "@lingui/babel-preset-react"
  ]
}
```

Everything is on the latest version. Thanks for any help!

**Comment by tricoder42** [comment] 2018-03-04 08:33
@bs1180 I just tried exactly the same config and I didn't get any error.

Could you please save output of `yarn list` or `npm list` to a file and upload it here?

**Comment by bs1180** [comment] 2018-03-05 10:31
@tricoder42 Thanks for checking - here's an example that reproduces it: https://github.com/bs1180/lingui-nextjs.

The output of `yarn list | grep lingui` is:
```
├─ @lingui/babel-plugin-extract-messages@2.0.5
│  └─ @lingui/conf@2.0.5
├─ @lingui/babel-plugin-transform-js@2.0.5
├─ @lingui/babel-plugin-transform-react@2.0.5
├─ @lingui/babel-preset-react@2.0.5
│  ├─ @lingui/babel-plugin-transform-js@2.0.5
│  └─ @lingui/babel-plugin-transform-react@2.0.5
├─ @lingui/cli@2.0.5
│  ├─ @lingui/babel-plugin-extract-messages@2.0.5
│  ├─ @lingui/babel-plugin-transform-js@2.0.5
│  ├─ @lingui/babel-plugin-transform-react@2.0.5
│  ├─ @lingui/conf@2.0.5
├─ @lingui/conf@2.0.5
├─ @lingui/core@2.0.5
├─ @lingui/react@2.0.5
│  ├─ @lingui/core@2.0.5
```

**Comment by ktunkiewicz** [comment] 2018-03-05 12:04
@tricoder42 sorry for late answer, our project does not have `.babelrc` to start with.
So, firstly, we don't use `.babelrc`. Babel configuration is done through webpack config.
Secondly, we use Babel 6. Didn't migrate to Babel 7 yet.

But why should that matter for lingui? It requires babel 7 and downloads it to `@babel` namespace. So our `node_modules` have both Babel 6 and Babel7. All other lingui components work find like this.
I would expect the `lingui` command line tool, which is kind of a "standalone" tool, not to care about project's Babel settings...

**Comment by tricoder42** [comment] 2018-03-06 06:14
@ktunkiewicz  Messages are extracted using babel plugin, so you need full babel config. It might be a problem that we're mixing babel6 and babel7 plugins. I would suggest extract babel config from webpack one. Similar workaround is needed for create-react-app, neutrino and all other 0config tools which hard-code babel config to webpack one.

I guess we might use a different method to extract messages, but take advantage of Babel AST and write a custom babel plugin was the easiest way to start.

@bs1180 I'll take a look, thanks for the repo!

**Comment by ipeo** [comment] 2018-03-07 13:07
I have th exact same issue

**Comment by Smolations** [comment] 2018-03-16 17:20
@tricoder42 I am having the same issue as @bs1180. I have tried node versions of 8.x and 9.x with the same result. Also tried using the plugins instead of the preset with no change. Is there a stable version of lingui that was written to work with babel6? If so, is there feature parity between that version and the current version?

**Comment by machour** [comment] 2018-03-22 14:22
@Smolations have you tried v2.0.2? Worked for me

**Comment by Smolations** [comment] 2018-03-22 17:04
@machour I did try downgrading to several versions actually, but no change. You have 2.0.2 working in a next.js project?

**Comment by machour** [comment] 2018-03-22 17:15
@Smolations react-native

**Comment by Photonios** [comment] 2018-03-24 14:02
We also faced this problem. The breaking change was in `@lingui/cli` 2.0.2. `@lingui/cli` 2.0.1 still works if you have a Babel 6 version.

More specifically, this commit used to make it work: https://github.com/lingui/js-lingui/commit/99f3f5daf640928941e62d05b9f1ac5dfa3ccf7d#diff-17502638c53a6f9c1aad8483bb8b2551

After that commit, `@lingui/cli` breaks for anyone who uses Babel 6.

**Comment by teodors** [comment] 2018-03-28 11:24
I am trying to run the `examples` and I get the same error. Also, there seems to be missing packages `babel-plugin-lingui-transform-js` and `babel-plugin-lingui-transform-react` for examples.

**Comment by srosset81** [comment] 2018-04-06 07:13
I have the same problem. Impossible to make `@lingui/cli` work with nextjs (5.1.0).
I tried all the 2.0.x versions of the CLI.

**Comment by Photonios** [comment] 2018-04-07 12:00
@srosset81 Version 2.01 should still work.

**Comment by adamgruber** [comment] 2018-04-17 18:03
@tricoder42 I did some digging on this and found that the problem does come from mixing plugins from Babel 6 and 7. The reason this happens is that inside the babel extractor, the method, `transformFileSync`, is called which attempts to load the user's `.babelrc` file. So, if a user's `.babelrc` file includes any presets/plugins meant for Babel 6 it fails and we get the error message.

The `transformFileSync` method  takes a `babelrc` option which, when set to `false`, will skip loading the user's config. The problem with this is then JSX files are not transformed since Babel doesn't load the preset for it. Lingui could be updated to include the React preset directly but we would still have issues if users need to transform their code with other presets/plugins.

One workaround is to use Babel's `env` feature to create a separate config for lingui. Example:
```json
{
    "env": {
        "development": {
            "presets": [
                "env",
                "react",
                "@lingui/babel-preset-react"
            ],
            "plugins": [
                "transform-object-rest-spread"
            ]
        },
        "lingui": {
            "presets": [
                "@babel/preset-react",
                "@lingui/babel-preset-react"
            ],
            "plugins": ["@babel/plugin-proposal-object-rest-spread"],
        }
    }
}
```

While this will work, it requires users to create separate blocks for `development` and `production` since Babel's default behavior of merging `env` options with non-env options will put us back where we started with mixed presets/plugins. 

In my opinion the best way forward here is to revert the Babel 7 change and release a new `2.X.X` version. Then, a `3.X.X` version can be released with Babel 7 added back in since it was a breaking change.

An alternative could be to update the `extract` command to accept some options to let users point to a specific babel config but this forces users to manage multiple configs which is not ideal.

**Comment by jmtt89** [comment] 2018-05-14 14:49
The same error thrown from project started with [create-react-app](https://github.com/facebook/create-react-app)

**Comment by adamgruber** [comment] 2018-05-15 15:12
@tricoder42 Any updates on this? It's currently a blocker for myself and anyone else unable to upgrade to Babel 7. Since Babel 7 is still in pre-release it doesn't seem to make sense for it to be a requirement.

**Comment by tricoder42** [comment] 2018-05-15 18:33
@adamgruber Absolutely. I'm planning releasing new version using Babel 6 with new major version using Babel 7 (even in beta). I'm just fixing some Babel-related issues, so once it's ready, I'm gonna publish it.

**Closed** 2018-07-22 13:32 UTC

**Comment by FredyC** [comment] 2018-08-24 15:34
Well, I just run into the same error not during extract call, but when I actually tried to import compiled `messages.js` into the CRA powered app. It does not make any sense why something like that would happen considering previous comments here. 😕

**Comment by tricoder42** [comment] 2018-08-25 04:57
@FredyC Could you create a minimal repo to reproduce the bug? That's really weird.

**Comment by FredyC** [comment] 2018-08-25 09:56
@tricoder42 Well looks like it's more like a general setup issue not related to Lingui. I cannot import any JS file. I've filed an issue here, but you can chime in if you have some ideas :)

https://github.com/wmonk/create-react-app-typescript/issues/382
