### ISSUE TITLE
[Pseudo Localization] Syntax tokens shouldn't be pseudo localized

### ISSUE THREAD

**Issue by nathanforce** [lingui/js-lingui#743] opened 2020-09-25 18:41 UTC
**Describe the bug**

Pseudolocalization mutates syntax tokens, for example in the follow `select` syntax the key "screener" is mutated as well as the `select` keyword.

```
Error: Can't parse message. Please check correct syntax: "Ŷōũŕ ƥŕōvĩďēŕ śēńţ à {0, śēĺēćţ, śćŕēēńēŕ {ŵēĺĺńēśś àśśēśśmēńţ} other {{assessmentType}}} ƒōŕ ŷōũ ţō ţàķē. Ƥĺēàśē ţàķē à ƒēŵ mĩńũţēś ţō ćōmƥĺēţē ţĥĩś àśśēśśmēńţ ƀēƒōŕē ŷōũŕ ńēxţ àƥƥōĩńţmēńţ."
```

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```
import { Trans } from "@lingui/react"

export default function App() {
   return (
    <div>
      Your provider sent a{' '}
            <Select
              value={isScreenerAssessment ? 'screener' : 'other'}
              screener="wellness assessment"
              other={assessmentType}
            />{' '}
            for you to take. Please take a few minutes to complete this
            assessment before your next appointment.
    </div>
}
```

**Expected behavior**
Syntax and tokens are unchanged, only actual language.

**Additional context**

- jsLingui version: 2.9.1

**Comment by tricoder42** [comment] 2020-09-30 19:14
This definitely shouldn't happen, thanks for report.

Could you please checkout `next` branch and test, if the problem persists in v3? If so, feel free to send PR, but please use `next` branch as a base (it should be relesed early November). Let me know if I can help somehow

**Comment by MartinCerny-awin** [comment] 2020-11-03 23:36
Hello @tricoder42 I can have a look at this issue

**Comment by tricoder42** [comment] 2020-11-04 07:47
@MartinCerny-awin Perfect, thanks a lot!

**Comment by pauloborges** [comment] 2021-01-25 22:01
Should this be really closed?

**Comment by semoal** [comment] 2021-01-25 22:42
Probably this issue is already fixed mate.

**Comment by pauloborges** [comment] 2021-01-26 06:38
Unfortunately no, the issue still happens with 3.4.0.

**Comment by semoal** [comment] 2021-01-26 08:28
oh, alright i'll take a look then

**Comment by MartinCerny-awin** [comment] 2021-01-26 09:07
I think Select is the last one that is missing. I am waiting for this issue to get fixed https://github.com/lingui/js-lingui/issues/919

@pauloborges is it Select that you are having issues with?

**Comment by pauloborges** [comment] 2021-01-26 09:31
@MartinCerny-awin, exactly!

**Comment by semoal** [comment] 2021-01-26 09:40
Okay i fix #919 asap

**Comment by semoal** [comment] 2021-01-26 19:05
@MartinCerny-awin #919 is merged feel free to improve select pseudolocaliaztion.

You can introduce this test:
```js
  it("Select", () => {
    expect(
      pseudoLocalize(
        "{gender, select, male {He} female {She} other {<span>Other</span>}}"
      )
    ).toEqual(
      "{0, select, male {Ĥē} female {Śĥē} other {<span>Ōţĥēŕ</span>}}"
    )
  })
```

**Closed** 2021-01-27 09:27 UTC
Labels: triage: accepted, 🐞bug, 📦 cli

**Comment by pauloborges** [comment] 2021-01-27 12:14
Awesome! Thanks for the quick fix!

A final question: any idea when a new release would be drafted?

**Comment by semoal** [comment] 2021-01-27 12:48
> Awesome! Thanks for the quick fix!
> 
> A final question: any idea when a new release would be drafted?

We like to release new version each Tuesday. So the next Tuesday will include this fix =)

**Comment by semoal** [comment] 2021-02-02 09:40
Released ^3.5.0

**Comment by pauloborges** [comment] 2021-02-03 14:48
Thanks! Upgraded it and it's working as intended.
