### ISSUE TITLE
Can't use t macro without default message

### ISSUE THREAD

**Issue by wilkinsonjack1993** [lingui/js-lingui#396] opened 2018-11-16 12:26 UTC
**Describe the bug**
When using the lingui <Trans> component like so:
```
<Trans id="message.delete">Delete</Trans>
<Trans id="message.delete" /> 
```
This will render the result: "DeleteDelete"

However, I expected when using the 'i18n.t' component, that the behaviour would be the same e.g.
```
i18n._(t('message.delete')`Delete`) 
i18n._(t('message.delete')) 
```
However, this fails when running the lingui extract command with error: 
`ReferenceError: Can't find variable: t
    in I18n (created by ...)
    in ... (created by ...)`

**To Reproduce**
Insert two instances of the i18n.t component with identical id's and run the lingui extract command. Something along the lines of:
```
import { t } from '@lingui/macro'
export default function App() {
  <I18n>
      {({ i18n }) => (
<button>{i18n._(t('message.delete')`Delete`)</button>
<button>{i18n._(t('message.delete'))</button>
)}
```

**Expected behavior**
Yarn extract completes and at runtime, the text for both the buttons will default to 'Delete'

**Comment by tricoder42** [comment] 2018-11-19 12:59
Hi @wilkinsonjack1993,
the problem is that template literal is expected after t('message.delete').

As a workaround, use `i18n._('message.delete')` instead of `i18n._(t('message.delete'))`.

**Comment by tricoder42** [comment] 2019-05-23 09:02
This is fixed in `next` version. See #499 and #334 for more info.

**Closed by tricoder42** 2019-05-23 09:02 UTC
Labels: 🐞bug, 📦 macro
