### ISSUE TITLE
[report] Production with Lingui v3

### ISSUE THREAD

**Issue by kopax-polyconseil** [lingui/js-lingui#1070] opened 2021-05-22 16:07 UTC
**Describe the bug**

Our project went to production this week, this ticket is made to track all the issue we have with lingui v3, and we have a lot

Todo: 
- [ ] : Cannot build application locally outside CI due to template literral not being interpolated locally
- [ ] : Lingui is editing test translation during during CI build:

```
 FAIL  src/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.test.tsx (1316 MB heap size)
  ● <PrivacyPolicyModal /> › should render correctly

    expect(received).toMatchSnapshot()

    Snapshot name: `<PrivacyPolicyModal /> should render correctly 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -258,11 +258,11 @@
                    }
                    testID="button-title"
                    textColor="#eb0055"
                    textSize={12}
                  >
    -               Politique des cookies
    +               Politique des cookies&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD
                  </Text>
                </View>
```

- [ ] Lingui is editing message during build

![image](https://user-images.githubusercontent.com/77674046/119233248-6efb9700-bb28-11eb-9da6-9434864aa153.png)

So far we are disabling lingui but we have pain to identify the root cause, as the CI and local build command are equal. This ticket is WIP, please keep it open.

**Comment by nakkamarra** [comment] 2021-05-26 00:57
I've run into this before. I don't think `Lingui is editing` anything, but rather examples looks like a merge conflict got committed in your source code. [The documentation calls this out] (https://lingui.js.org/ref/conf.html?highlight=merge%20conflict#lingui) and if you check your source code / catalog files, there is probably some unwanted instance `HEAD` there. You should take care to check for merge conflicts in the source and catalogs before committing. 

As far as `template literral not being interpolated locally`, if you'd provide an example, someone might be able to debug or provide a solution.

**Comment by semoal** [comment] 2021-05-26 08:05
Yeah actually I was going to say the same about the first part, sometimes .po files gets conflicts and that >>>>> strings came from there.

About template literals not being interpolated locally was an issue with ESM builds, Lingui needs a development runtime to make it work and another for production, when I've introduced ESM I forgot to export that ESM development and just published ESM production...

Since 3.9.0 it's fixed, https://github.com/lingui/js-lingui/pull/1059

**Comment by kopax-polyconseil** [comment] 2021-05-26 08:14
Hi @semoal , we'll definitely try to upgrade to 3.9.0 asap.

Some of the errors we had were happening when generating the messages.po on a up to date branch. Since, we had to unplug some translation not to risk to display those. 

I'll improve the report as soon as we'll have time to investigate the translation issues we have. Thanks!

**Comment by kopax-polyconseil** [comment] 2021-06-01 15:26
Hi @semoal, we just tested 3.9.0 and we still see the is not a function error on the same string as before in development. 

I presume #1042 should be re-opened.

**Comment by vonovak** [comment] 2021-06-14 22:55
Not that anyone asked for my opinion but I circled here browsing through the repo and reading https://github.com/lingui/js-lingui/issues/1022

I just wanted to give @semoal a friendly recommendation to think carefully before spending time with issues that do not provide clear reproduction steps (as explained in https://stackoverflow.com/help/minimal-reproducible-example). It appears that you even refactored the app in question to v3 in a _huge_ PR and maybe even did that for free (!) - I admire such maintainer involvement but I just wanted to let you know that you could easily burn out doing too much of this kind of stuff. 

Unfortunately, in my experience, people often take open source as a place to come for free tools and support. So please just make sure to take care of yourself and your mental health 👍 🙂

**Closed** 2021-08-21 02:55 UTC
Labels: wontfix
