### ISSUE TITLE
Default message in PO file not set when merging

### ISSUE THREAD

**Issue by chinchang** [lingui/js-lingui#383] opened 2018-11-01 22:52 UTC
**Describe the bug**
I have this in my component using the `Trans` component:

```
<Trans id="console.title" defaults="Console" />
```

Extracting from above I expect this:

```
msgid "console.title"
msgstr "Console"
```

instead it generates:

```
msgid "console.title"
msgstr ""
```

If the default is not filled in translation, then how would a translator know the source string.

**To Reproduce**
As mentioned above.

**Expected behavior**

In my po file:

```
msgid "console.title"
msgstr "Console"
```

**Additional context**

- jsLingui version ``lingui --version``: 2.7.0
- Babel version ``npm list babel-core``: ├── babel-core@7.0.0-bridge.0
├─┬ babel-minify@0.2.0
│ └── babel-core@6.26.3
├─┬ jest@21.2.1
│ └─┬ jest-cli@21.2.1
│   └─┬ jest-runtime@21.2.1
│     └── babel-core@6.26.3
└─┬ preact-cli@2.2.1
  └─┬ babel-register@6.26.0
    └── babel-core@6.26.3

**Comment by tricoder42** [comment] 2018-11-01 23:10
Well, this is tricky.

Convention is that `msgid` is source and `msgstr` is translation. Filling source into translation is just odd. That's the drawback of using keys as sources: translator needs to see two catalogs, one for source language (EN) and one for target one.

If we add default message to `msgstr`, then we can't tell easily if all messages are translated or if any translation is missing.

I believe we could solve it by adding `fuzzy` flag, which in general means "require translators attention". Django web framework uses it when it automatically copy translation from obsolete `msgid` (i.e. when you rename `console.title` to `app.console.title` in the code).

1. New entries would be always `fuzzy` with default message filled in as translation.
2. Translator then has to go through the fuzzy entries and translate/check them.
3. CLI reports all `fuzzy` entries as untranslated and `lingui compile --strict` throws an error

It's just a proposal. I havent' seen a tool which fills source messages to translations, but I understand the problem.

**Comment by chinchang** [comment] 2018-11-02 05:30
@tricoder42  Appreciate your super quick response!

Well, I forgot to mention that the behaviour would be very correct for only the set source locale. If I have `"sourceLocale": "en"` set in my `.linguirc` you'll notice extract reports 0 missed translations for that particular locale. So it also makes sense that the translations are prefilled from source code because that locale anyways doesn't need to be translated.

**Comment by tricoder42** [comment] 2018-11-02 06:05
That makes sense!

I'm looking at the code, at it is supposed to work like that

https://github.com/lingui/js-lingui/blob/7e53688490ccb8ec981fcfd7a10a9fdc4dd9153f/packages/cli/src/api/catalog.js#L66-L73

It might be caused by `deserialize` method in `po.js`, which does extract `defaults` prop.

https://github.com/lingui/js-lingui/blob/7e53688490ccb8ec981fcfd7a10a9fdc4dd9153f/packages/cli/src/api/formats/po.js#L49-L71

Just curious: When you extracted the messages for the first time did you already have `sourceLocale` set? Or did you set it after you run `lingui extract`? In either way, could you please try to remove all messages in catalog for source locale and run `lingui extract` again? Just to make sure if the bug is when *new messages* are added or when *existing messages* are merged.

Thank you!

**Comment by tricoder42** [comment] 2018-11-02 06:35
Yeah, that's expected. It is allowed to edit catalog for `sourceLocale` manually to fix messages without touching the code. This makes it hard to update automatically, because we can't tell if the message was changed by translator or by developer in the code.

There is however [--overwrite](https://lingui.js.org/ref/cli.html#cmdoption-extract-overwrite) option for `lingui extract` which force updates translations for sourceLocale from source.

Anyway, thank you for bug report. In short: the problem is that default messages aren't updated correctly.

**Comment by chinchang** [comment] 2018-11-02 06:37
Cool! I'll try that option. Thanks for your help and this awesome library @tricoder42 :)

**Comment by tricoder42** [comment] 2018-11-02 06:39
I'll keep it open because there's still a bug

**Additional context**
- Only happens when merging existing catalogs.
- Might be related to this code, which is missing `defaults` prop: https://github.com/lingui/js-lingui/blob/7e53688490ccb8ec981fcfd7a10a9fdc4dd9153f/packages/cli/src/api/formats/po.js#L49-L71

**Closed** 2020-11-05 08:31 UTC
Labels: wontfix, 🐞bug, 📦 cli
