### ISSUE TITLE
Nested Plural and Trans

### ISSUE THREAD

**Issue by ghostd** [lingui/js-lingui#372] opened 2018-10-26 08:25 UTC
Hi,

I don't know if i misread the [documentation](https://lingui.js.org/tutorials/react.html#variables-and-components) or if it's a bug.

I did copy/paste the following example from the documentation:
```
<p>
   <Plural
      value={messagesCount}
      one={`There's # message in your inbox, ${name}`}
      other={<Trans>There're <strong>#</strong> messages in your inbox, {name}</Trans>}
   />
</p>
```

When i extract the translations i get:
```
msgid "{messagesCount, plural, one {There's # message in your inbox, {name}} other {}}"
msgstr "" // here i copied the id
```

So when the count is '1', i get the correct translation (with the correct values). If i force the `value` attribute to `2` i got nothing (empty string).

**Comment by FredyC** [comment] 2018-10-26 10:11
Have you used Trans from `@lingui/macro` or from `@lingui/react`? I haven't tested this out yet, but it might work with macros only.

**Comment by ghostd** [comment] 2018-10-26 10:53
You're right, i forgot to mention i use the macro.

**Comment by ghostd** [comment] 2018-10-27 10:10
I pasted this code into the `webpack-react` example :
```
<p>
   <Plural
      value={messagesCount}
      one={`There's # message in your inbox, ${name}`}
      other={<Trans>There're <strong>#</strong> messages in your inbox, {name}</Trans>}
   />
</p>
```

When i re-run the messages extraction, i don't get a new entry.

**Comment by ghostd** [comment] 2018-10-28 15:39
I get the expected behavior for my use case with the following syntax:
```
<Trans id="messages.count">
   <Plural
      value={messagesCount}
      one={`There's # message in your inbox, ${name}`}
      other={<Trans>There're <strong>#</strong> messages in your inbox, {name}</Trans>}
   />
</Trans>
```

**Comment by tricoder42** [comment] 2018-10-28 23:09
Hey @ghostd, this is definitely a bug. I'm just refactoring macros, so I'll take a look.

**Comment by simonlc** [comment] 2019-02-18 00:05
Any progress on this? I'm running into the same issue. I've tried using macros and the react versions, though neither work.

**Comment by Skippidar** [comment] 2019-03-15 11:20
Got same bug. 
Had to set "few" and "many" props, then translations appeared. As I can see, empty (or not set) "few"\"many" prop doesn't result in fallback to "other" prop.

**Comment by VinSpee** [comment] 2020-01-30 14:20
Hmm, I'm running into this issue as well, but I added "few" and "many" and am still getting a "missing" warning, even w/ fallbackLocale and sourceLocale specified:

## .linguirc.js:
```js
module.exports = {
  localeDir: '__generated__/locales',
  srcPathDirs: ['src'],
  format: 'po',
  fallbackLocale: 'en',
  sourceLocale: 'en',
  pseudoLocale: 'en-PL',
};
```

## component.tsx
```tsx
import { Trans, Plural } from '@lingui/macro';
…
<Trans id="speakers.count">
    About the{' '}
    <Plural
	value={data.video.presenters.length}
	one={<Trans>speaker</Trans>}
	few={<Trans>speakers</Trans>}
	many={<Trans>speakers</Trans>}
	other={<Trans>speakers</Trans>}
    />
</Trans>

```

## generated messages.po:

### source locale (en):
```po
#: src/components/slug/info-details.tsx:57
msgid "speakers.count"
msgstr "About the {0, plural, one {speaker} few {speakers} many {speakers} other {speakers}}"
```

### pseudo locale (en-PL):
```po
#: src/components/slug/info-details.tsx:57
msgid "speakers.count"
msgstr ""
```

In the ui, I'm seeing the "fallback" text applied in `I18nProvider` no matter which locale is active:

![image](https://user-images.githubusercontent.com/582828/73457389-9b8f0c80-4341-11ea-802b-6ad003243adb.png)

![image](https://user-images.githubusercontent.com/582828/73457510-c5483380-4341-11ea-8c5c-1b0da4f0cd64.png)

any workarounds?

**Comment by crhayes** [comment] 2020-06-02 20:19
This may be related to @VinSpee's problem. I've noticed a problem when using `<Trans>` nested within `<Plural>`.

It seems as though import order matters:

```ts
import { Plural, Trans } from '@lingui/macro'; // results in correct behaviour
import { Trans, Plural } from '@lingui/macro'; // results in incorrect behaviour
```

Given the following translation:

```jsx
<Plural
  value={totalCount}
  one={
    <Trans>
      <strong>#</strong> Issue
    </Trans>
  }
  other={
    <Trans>
      <strong>#</strong> Issues
    </Trans>
  }
/>
```

When I import in the "incorrect order", I get the following:
```js
// Trans before Plural
import { Trans, Plural } from '@lingui/macro';

msgid "{0, plural, one {} other {}}"
msgstr "{0, plural, one {} other {}}"
```

When I import in the "correct order", I get the following:
```js
// Plural before Trans
import { Plural, Trans } from '@lingui/macro';

msgid "{0, plural, one {<0>#</0> Issue } other {<1>#</1> Issues }}"
msgstr "{0, plural, one {<0>#</0> Issue } other {<1>#</1> Issues }}"
```

The latter example here is what I expect in both scenarios.

We are using:
- React
- Typescript
- Lingui 2.9.1
- `@lingui/loader`
- `babel-plugin-macros`

**Comment by FredyC** [comment] 2020-06-02 20:41
Yea, macros tend to suffer from ordering issues. It's kinda logical when you think about it. If `Trans` is first, it does its job of core transformation, and then `Plural` does its part but `Trans` no longer has an option to see that.

Honestly, I don't about any good solution for that. Only that `Trans` would need to analyze more deeply and if it sees a "known" macro, it would scream a warning.

**Comment by tricoder42** [comment] 2020-06-03 05:39
This is already fixed in v3 (please checkout pre-release #334).

Ordering of imports doesn't matter, the top-most macro is always processed first and "consumes" all inner macros.

**Closed by tricoder42** 2020-06-03 05:39 UTC
Labels: 🐞bug

**Comment by N1kto** [comment] 2020-08-05 18:42
Hello guys. I have a similar issue (or maybe not). I have all working fine locally, but on production, something is wrong:
Local server:
![Screenshot from 2020-08-05 20-30-24](https://user-images.githubusercontent.com/5045863/89450247-88c71b80-d75a-11ea-9b33-2d5f712389b1.png)

Production:
![Screenshot from 2020-08-05 20-33-09](https://user-images.githubusercontent.com/5045863/89450498-ebb8b280-d75a-11ea-85c4-98998c9f342b.png)


Component:

```
import { Trans, Plural, t } from '@lingui/macro';

<Alert>
  <p>
    <Trans>
      Are you sure you want to delete <strong>{selectedRows.length}</strong>{' '}
      <Plural value={selectedRows.length} one="reference" other="references" />
    </Trans>
    ?
  </p>
  <p>
    <strong>
      <Trans>THIS OPERATION IS IRREVERSIBLE</Trans>!
    </strong>
  </p>
</Alert>
```
If I change the import order as suggested above, that is to `import { Plural,Trans, t } from '@lingui/macro';`
The local output is following:
![Screenshot from 2020-08-05 20-23-46](https://user-images.githubusercontent.com/5045863/89450391-bf9d3180-d75a-11ea-9624-ce31d643cfec.png)
The production:
![Screenshot from 2020-08-05 20-24-13](https://user-images.githubusercontent.com/5045863/89450523-f5dab100-d75a-11ea-99a0-ad8a7e2ee8e3.png)

Could you suggest what can be an issue here? I thought that maybe since '@lingui/macro';` is a dev-dependency, it's not installed during the production build, but if I import from '@lingui/react';` then it stops rendering anything where `<Trans>` is used:
![Screenshot from 2020-08-05 20-37-18](https://user-images.githubusercontent.com/5045863/89450890-992bc600-d75b-11ea-9f6e-a41356428a94.png)

One may wonder, why dialog buttons have test then. For their labels I don't use `<Trans>`, but `i18n._(t`Cancel`)`.

What can be the cause of such undesired behavior?

P.S. I am using `ligui` packages version 2.9.1 within `create-react-app` version 3.4.0.

**Comment by cdohotaru** [comment] 2021-02-11 09:49
@N1kto Late to the party but I had the exact same issue and hopefully this helps somebody in the future. 

In my project there is a command which is run to generate the .po files. This command reads several .json configuration files and create the messages.po files based on the content of those files. The config looks something like this:
`{
  "compileNamespace": "cjs",
  "localeDir": "src/features/my-list/@locales",
  "srcPathDirs": [
    "src/features/my-list",
    "src/features/my-list-item",
    **"src/features/@common_components/dialogs"**
  ],
  "format": "po",
  "fallbackLocale": "en",
  "sourceLocale": "de",
  "formatOptions": {
    "origins": false
  },
  "locales": [
    "de",
    "en",
    "it"
  ]
}`

The project is split in several folders and as per my understanding, these files create associations between different components in different folders. 
In my case I had a plural used in a component in "@common_components/dialogs" but because there was no association between the common folder where the dialog is and the caller of that dialog in a totally different folder, the required string were not generated in the .po files. 
This was not reproducible locally but I don't know exactly why. Anyway, I added the bolded line in the config above which made the script file generate the right strings in the .po files.
The association goes from the place where the <Plural> tag is being created to the place where it will actually be rendered (from a folder perspective). That is, the config above says "I will use in my-list a component from @common_components/dialogs".

Hope this helps.
