### ISSUE TITLE
Vietnamese support | bug

### ISSUE THREAD

**Issue by seeden** [lingui/js-lingui#1033] opened 2021-04-08 15:18 UTC
From unknown reason lingui is not able to compile few Vietnamese strings.
It is working fine when I remove it from my .po file.
I am using latest version 3.8.2

Here is content of .po file
```po
#: src/components/farm/FarmYourHarvesterNetwork.tsx:58
msgid "A harvester is a service running on a machine where plot(s) are actually stored. A farmer and harvester talk to a full node to see the state of the chain. View your network of connected harvesters below Learn more"
msgstr "Harvester là một dịch vụ chạy trên một  máy chứa các tệp plot  . Một \bfarmer và harvester tương tác với một nút đầy đủ để xác định trạng thái của chuỗi. Xem các harvester được kết nối của bạn dưới đây Tìm hiểu thêm"


#: src/electron/main.ts:296
msgid "Contribute on GitHub"
msgstr "Đóng góp qua GitHub"
```

I see next error stacktrace:
```sh
/Users/seeden/Documents/git/chia-blockchain/chia-blockchain-gui/node_modules/@lingui/cli/api/compile.js:89
    throw new Error("Can't parse message. Please check correct syntax: \"".concat(message, "\""));
    ^

Error: Can't parse message. Please check correct syntax: "Đóng góp qua GitHub"
    at compile (/Users/seeden/Documents/git/chia-blockchain/chia-blockchain-gui/node_modules/@lingui/cli/api/compile.js:89:11)
    at /Users/seeden/Documents/git/chia-blockchain/chia-blockchain-gui/node_modules/@lingui/cli/api/compile.js:45:51
    at Array.map (<anonymous>)
    at createCompiledCatalog (/Users/seeden/Documents/git/chia-blockchain/chia-blockchain-gui/node_modules/@lingui/cli/api/compile.js:37:43)
    at /Users/seeden/Documents/git/chia-blockchain/chia-blockchain-gui/node_modules/@lingui/cli/lingui-compile.js:91:66
    at Array.forEach (<anonymous>)
    at /Users/seeden/Documents/git/chia-blockchain/chia-blockchain-gui/node_modules/@lingui/cli/lingui-compile.js:61:14
    at Array.forEach (<anonymous>)
    at command (/Users/seeden/Documents/git/chia-blockchain/chia-blockchain-gui/node_modules/@lingui/cli/lingui-compile.js:50:18)
    at compile (/Users/seeden/Documents/git/chia-blockchain/chia-blockchain-gui/node_modules/@lingui/cli/lingui-compile.js:135:12)
```

**Comment by semoal** [comment] 2021-04-08 15:40
Could you give me the current message which is causing the error? So i can add it to the testing suite -> reproduce -> and fix it =)

**Comment by seeden** [comment] 2021-04-08 16:03
It is already in the description.

```po
#: src/components/farm/FarmYourHarvesterNetwork.tsx:58
msgid "A harvester is a service running on a machine where plot(s) are actually stored. A farmer and harvester talk to a full node to see the state of the chain. View your network of connected harvesters below Learn more"
msgstr "Harvester là một dịch vụ chạy trên một  máy chứa các tệp plot  . Một \bfarmer và harvester tương tác với một nút đầy đủ để xác định trạng thái của chuỗi. Xem các harvester được kết nối của bạn dưới đây Tìm hiểu thêm"


#: src/electron/main.ts:296
msgid "Contribute on GitHub"
msgstr "Đóng góp �qua GitHub"
```

**Comment by semoal** [comment] 2021-04-08 16:22
Looks like the issue is our dependency `messageformat-parser` which is used for parsing the ICU messages
I'll try to analyze if we can workaround around Lingui and if not, we'll have to open an issue there

**Comment by semoal** [comment] 2021-04-08 16:34
Looks like I found an "easy" fix, i'll create a release in a few minutes.

**Comment by semoal** [comment] 2021-04-08 16:41
Alright, we don't need to change anything. Just remove that \b from the msgstr is not valid

**Comment by semoal** [comment] 2021-04-08 16:44
https://github.com/lingui/js-lingui/commit/9b2705feada95f5272346bacee54a26b5518af5e
Just pushed a commit for improving the log if some syntax is not valid. :)

Will be released in a few minutes

**Comment by seeden** [comment] 2021-04-08 17:07
This is not work as well and it is without \b

```po
#: src/electron/main.ts:296
msgid "Contribute on GitHub"
msgstr "Đóng góp �qua GitHub"
```

Can you check it as well? Thank you

**Comment by semoal** [comment] 2021-04-08 17:20
I can't see that character mate, dunno how to test it hehe
![Screenshot 2021-04-08 at 19 20 16](https://user-images.githubusercontent.com/22656541/114069638-80058700-989f-11eb-8f97-d159b5514987.png)

**Comment by semoal** [comment] 2021-04-08 17:23
https://stackblitz.com/edit/typescript-9kphuq?devtoolsheight=33&file=index.ts
You can use this website to test if that library is the problem or not =)

**Comment by seeden** [comment] 2021-04-08 17:29
It is not working https://stackblitz.com/edit/typescript-9x4cdq?devtoolsheight=33&file=index.ts

**Comment by semoal** [comment] 2021-04-08 17:37
Alright then, I'll create a bug in his repository. I've tried with his new version which is in beta and works good, but it's a major release and breaks lingui so i'll have to find time to work on it :/

**Comment by seeden** [comment] 2021-06-14 20:21
still an issue

**Comment by Martin005** [comment] 2023-01-07 22:18
Hello @seeden!
Could you please confirm whether this issue still persists?

**Closed** 2023-01-11 12:14 UTC
Labels: bug, ↻ awaiting response
