### ISSUE TITLE
CLI command `extract --overwrite` deletes msgstr values in source locale po file

### ISSUE THREAD

**Issue by jedrichards** [lingui/js-lingui#616] opened 2020-02-08 11:50 UTC
**Describe the bug**

The first time `lingui extract --overwrite` is run then it generates po file entries for the source locale with identical `msgid` and `msgstr` values, e.g.

```
#: src/file.ts:105
msgid "Hello world"
msgstr "Hello world"
```

But then future runs of `lingui extract --overwrite` will remove the `msgstr` values in existing unedited entries, and changes the above to,

```
#: src/file.ts:105
msgid "Hello world"
```

This renders the source locale po file seemingly invalid, and breaks integrations with some cloud translation services like CrowdIn with errors like `The imported messages.po localization file is invalid. GetText PO validation module said: line ###: missing msgstr section`.

**To Reproduce**

Config looks like

```
module.exports = {
  sourceLocale: 'en',
  srcPathDirs: ['<rootDir>/src'],
  format: 'po',
  sorting: 'origin',
  localeDir: '<rootDir>/src/locale',
}
```

And we're just using the plain JS approach (not React), e.g.

```
import { t } from '@lingui/macro'
i18n._(t`Hello world`)
```

**Expected behavior**

Repeated runs of `lingui extract --overwrite` do not remove `msgstr` entries for existing translations in the source locale po file. Although this is an assumption, and my understanding of the process may be faulty.

**Additional context**

- jsLingui version `2.9.1`
- Babel version `babel-core@7.0.0-bridge.0`
- Your Babel config

```
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          node: '10',
        },
        modules: 'cjs',
      },
    ],
    '@babel/typescript',
  ],
  plugins: [
    '@babel/proposal-class-properties',
    '@babel/proposal-object-rest-spread',
    'macros',
  ],
}
```

**Comment by toolness** [comment] 2020-05-26 13:30
Thanks for reporting this, I actually ran into the same problem myself.  Until it's fixed, I'm working around it by post-processing the PO file after `lingui extract` using the same PO parsing/serialization library that lingui uses: https://github.com/JustFixNYC/tenants2/pull/1486.

**Comment by ThiefMaster** [comment] 2020-11-02 12:07
any update on this? I don't think it should be [wontfix]...

**Comment by tricoder42** [comment] 2020-11-02 12:48
@ThiefMaster Is it still hapenning in v3? The only reason why it's marked as `wontfix` is that it wasn't updated for a very long time.

**Comment by ThiefMaster** [comment] 2020-11-02 12:50
tested with `3.0.0-21`; haven't tried the latest version yet ;o

**Comment by tricoder42** [comment] 2020-11-02 12:56
Yeah, `cli` haven't changed much since that version. Let's assume this bug is still present. I'm not going to have enough time to work on it this week. If anyone has a spare time, feel free to dive in and send a PR.

**Comment by ThiefMaster** [comment] 2020-11-03 09:40
```patch
diff --git a/packages/cli/src/api/catalog.ts b/packages/cli/src/api/catalog.ts
index 5b3957fe..93cfa90c 100644
--- a/packages/cli/src/api/catalog.ts
+++ b/packages/cli/src/api/catalog.ts
@@ -192,7 +192,7 @@ export class Catalog {
             options.overwrite)

         const translation = updateFromDefaults
-          ? nextCatalog[key].message
+          ? key
           : prevCatalog[key].translation

         return {
```

This seems to fix it - the `nextCatalog` entries only have an `origin` but no `message`.

**Comment by semoal** [comment] 2020-11-05 14:17
@ThiefMaster could you provide a reproduction repo like a sandbox or something similar? Couldn't reproduce any issue with overwrite in the cra example of js-lingui

**Closed** 2021-01-11 16:06 UTC
Labels: triage: accepted, wontfix, 🐞bug, 📦 cli
