### ISSUE TITLE
Allow defaults to be lazy

### ISSUE THREAD

**Issue by tkvw** [lingui/js-lingui#341] opened 2018-09-25 20:07 UTC
I like to do nested lookup, currently I do this: 
```
i18n._({ 
     id: "resource.user.fields.username.label",
     defaults: i18n._({id: "fields.username.label",defaults: "Username"})
})
```
But this always resolves the default, I like this to be lazy:  
```
i18n._({ 
     id: "resource.user.fields.username.label",
     defaults: i18n => i18n._({id: "fields.username.label",defaults:"Username"})
})
```
Thoughts ? 
(I think it's relatively easy to implement)

**Comment by tricoder42** [comment] 2018-09-25 20:14
That's actually tricky, because defaults are removed from compiled catalogs. All defaults and fallbacks are resolved at compile time.

So, basically we wan to have a fallback ID, right? We're either looking for generic message (fields.username.label) which might be overridden by specific one (resource.user.fields.username.label) with final faallback to "Username".

Somethink like, take first from:
resource.user.fields.username.label

**Comment by tkvw** [comment] 2018-09-25 20:20
I am requesting this for a different use case; I have a generic component, i.e.: `<List resource="user">` and the message id's are constructed from the resource prop. So no possibility for extracting the messages, but the format is predefined, so easily to construct; 
```
resources.user.title=
resources.user.fields.username.label=
resource.user.fields.username.validation.required=
resources.user.fields.username.placeholder=
types.creditcard.placeholder=
validation.required=
...etc 
```

**Comment by tricoder42** [comment] 2018-09-26 04:53
The problem is `defaults` prop is completely removed from the source code. I think if the `defaults` is anything but string, we could leave it there.

Just curious, how do you create message catalogs in your case?

**Comment by tkvw** [comment] 2018-09-30 08:29
So, I am not using the macros for this situation, but use the `i18n` instance directly. The message catalogs are generated manually; A component will render according to availability of i18n messages, i.e.: 
```
resources.user.fields.username.placeholder=Please enter your username
resources.user.fields.username.help=Your username is issued by email
```
If the `placeholder` or `help` message is not available the `Fieldcomponent` will not render the props. This requires a lot of defaults lookup, that's why I want them to be lazy.

**Comment by tricoder42** [comment] 2018-10-10 13:48
I see. We have to figure out the API to handle situations like this. Right now, defaults and fallbacks are resolved at build time. Runtime catalog is simple id->translation mapping.

**Comment by tkvw** [comment] 2018-10-10 15:03
Yeah, so I discovered this when moving from development to production; the parameterized messages didn't get interpreted. 

The only way to share state between client and ssr is by a serializable object (json). So for this I need to compile the messages on the client side. Another solution would be to async require the messages, but then the initial (ssr) render wouldn't have any messages or to simply include all message catalogs, but that doesn't scale. 

Anyway for now I switched to `i18next` to handle the translations in my page, because it uses plain json catalogs.

**Comment by tricoder42** [comment] 2018-10-10 15:04
Alright, closing this for now 👍

**Closed by tricoder42** 2018-10-10 15:04 UTC

**Comment by tkvw** [comment] 2018-10-10 15:08
It would be interesting to have a `create compiler` macro which creates a compiler for selected locales. This compiler could be used on a json catalog on the client on first render.

**Comment by tricoder42** [comment] 2018-10-10 15:13
There's already open issue for it #342. It might be easy to do by exporting compiler in subpackage as described here: https://github.com/lingui/js-lingui/issues/342#issuecomment-424687026. There're might be few problems to solve, because `lingui compile` does few more things on top of compiling messages, as described at the end of [this comment](https://github.com/lingui/js-lingui/issues/342#issuecomment-424675928).

**Comment by tkvw** [comment] 2018-10-10 16:44
> There're might be few problems to solve, because lingui compile does few more things on top of compiling messages, as described at the end of this comment.

That's why I said a `create compiler` macro, which would generate a `compiler.js` (like the compiled catalogs) which contains the pluralize methods for the selected locales. This would allow the compiler to be small and support the required locales. But that's just an idea.
