### ISSUE TITLE
No messages extracted when running 'lingui extract'

### ISSUE THREAD

**Issue by shye0000** [lingui/js-lingui#105] opened 2017-10-23 09:55 UTC
Hi, I followed the documentations to configure my react application but I got an error when running 'lingui extract':
```
Extracting messages from source files…
Collecting all messages…
fs.js:914
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/home/li@wbc2.local/VM/test-project-api-platform/front-admin-on-rest/locale/_build'
    at Object.fs.readdirSync (fs.js:914:18)
    at collect (/usr/local/lib/node_modules/lingui-cli/dist/api/extract.js:71:23)
    at command (/usr/local/lib/node_modules/lingui-cli/dist/lingui-extract.js:56:38)
    at Object.<anonymous> (/usr/local/lib/node_modules/lingui-cli/dist/lingui-extract.js:97:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

Here is my .babelrc
```
{
  "presets": [
    "es2015",
    "react",
    "stage-3",
    "lingui-react"
  ],
  "plugins": [
    "syntax-dynamic-import",
    "transform-runtime",
    "transform-class-properties",
    "lodash",
    "transform-object-assign",
    "transform-object-rest-spread",
    "transform-export-extensions",
    "transform-class-properties",
    "react-hot-loader/babel",
    ["resolver", {"resolveDirs": ["src", "src/modules"]}]
  ],
  "env": {
    "test": {
      "plugins": ["dynamic-import-node"]
    }
  }
}
```
And here is my lingui configuration in package.json:
```
"lingui": {
    "localeDir": "<rootDir>/locale",
    "srcPathDirs": [
      "<rootDir>/src"
    ]
  }
```

Did I do something wrong? Does anyone has the same error? Thanks in advance for your helps.

**Comment by tricoder42** [comment] 2017-10-23 10:17
Seems like there's a bug when no messages are extracted from source files. I've just pushed a [fix](https://github.com/lingui/js-lingui/pull/106), it should be released test suit finishes.

**Comment by shye0000** [comment] 2017-10-23 10:29
@tricoder42 Yes I tried the new version 1.3.7, the error is gone. 
![image](https://user-images.githubusercontent.com/6414361/31884419-3f75ba2a-b7ed-11e7-8b45-1246d818f488.png)

But I got another issue here, 0 message extracted.
And I my code I have Trans defined like this:
![image](https://user-images.githubusercontent.com/6414361/31884516-97e02f88-b7ed-11e7-9ac3-a6aeaf8bb60f.png)

**Comment by tricoder42** [comment] 2017-10-23 13:41
@shye0000 Indeed, this seems to be another bug. Do you import Trans from `lingui-react`? Could you please paste the import section of your file?

**Comment by shye0000** [comment] 2017-10-23 14:11
@tricoder42 Here is the file I tested:
filename: LayoutComponent.js
```
import React from 'react';
import {Trans} from 'lingui-react';
import {logout} from 'utils/JWTAuthentification/actions';
import {userIsAuthenticated} from 'utils/JWTAuthentification/auth';
import {connect} from 'react-redux';
import {NavLink, Link} from 'react-router-dom';
import {renderRoutes} from 'react-router-config';
import './styles/layout.scss';

const LogoutLink = userIsAuthenticated(({logout}) => <button
	onClick={() => {
		logout();
	}}
>Logout</button>);

const mapStateToProps = (state) => {
	return {authData: state.user.data};
};

class LayoutComponent extends React.Component {

	constructor(props) {
		super(props);
		this.toggleSideMenu = this.toggleSideMenu.bind(this);
		this.state = {
			sideMenuShrink: true
		};
	}

	toggleSideMenu(forceOpen) {
		this.setState({
			sideMenuShrink: forceOpen ? false : !this.state.sideMenuShrink
		});
	}

	render() {
		return (
			<div className="app-container">
				<header className="header">
					<div className="left">
						<div className="mobile-menu-icon" onClick={() => this.toggleSideMenu(true)}>M</div>
						<Link to={`${AppConfig.appBaseRoute}`}>Webcentric R&D - A demo application with React &
							Api-Platform</Link>
					</div>
					<div className="right">
						<LogoutLink logout={logout}/>
					</div>
				</header>
				<div className="app-body-wrapper">
					<div className={'side-menu ' + (this.state.sideMenuShrink ? 'shrink' : 'open')}>
						<div className="menu-item close" onClick={() => this.toggleSideMenu(false)}>
							<div className="close-icon"> {'<'} </div>
						</div>
						<div className="menu-items-wrapper">
							<NavLink className="menu-item" to={`${AppConfig.appBaseRoute}books`}>
								<span>
									<Trans id="app.books">Books</Trans>
								</span>
							</NavLink>
							<NavLink className="menu-item" to={`${AppConfig.appBaseRoute}authors`}>
								<span>
									<Trans id="app.authors">Authors</Trans>
								</span>
							</NavLink>
						</div>
					</div>
					<div className="app-content">
						{renderRoutes(this.props.route.routes)}
					</div>
				</div>
			</div>
		);
	}
}

export default connect(mapStateToProps)(LayoutComponent);
```

**Comment by tricoder42** [comment] 2017-10-23 14:27
I tried this file with your `lingui` configuration and got 2 messages extracted:

<img width="503" alt="snimek obrazovky 2017-10-23 v 16 25 07" src="https://user-images.githubusercontent.com/827862/31894469-d655d63e-b80e-11e7-8a40-fe2f7c2c4c11.png">

So, what platform you're on? Linux/Windows?
Do you run `lingui extract` in the same directory where do you have `src` directory?
What's the output of `lingui extract --verbose` command?

**Comment by shye0000** [comment] 2017-10-23 14:37
@tricoder42 I'm on Linux and yes I run lingui extract in the same directory as the 'src' directory.
Here is the screen shot of the output in verbose mode:
![image](https://user-images.githubusercontent.com/6414361/31894992-4aed0232-b810-11e7-8944-8430ffdcc565.png)

**Comment by tricoder42** [comment] 2017-10-23 14:39
If you look inside `locale` directory, is there `_build` subdirectory? If so, what's the content of `LayoutComponent.json`?

**Comment by shye0000** [comment] 2017-10-23 14:43
@tricoder42 The subdirectory `_build` is created, but its empty without `LayoutComponent.json`.
![image](https://user-images.githubusercontent.com/6414361/31895267-080b3460-b811-11e7-817b-2bd3e58e8f7b.png)

**Comment by shye0000** [comment] 2017-10-23 14:59
@tricoder42 Here is my project structure, maybe it helps? :)
![image](https://user-images.githubusercontent.com/6414361/31896230-883f8224-b813-11e7-811c-be2ba2c98d69.png)

**Comment by tricoder42** [comment] 2017-10-23 15:08
@shye0000 It all seems to be good.

Could you please try:
1. Clone this repo `git@github.com:lingui/js-lingui.git`
2. Go to `examples/webpack-react` directory
3. Delete `locale` directory
4. Add locales `lingui add-locale en fr`
5. And finally run `lingui extract`?

**Comment by tricoder42** [comment] 2017-10-23 15:22
Also, could you please paste here output of `npm list` command?

**Comment by shye0000** [comment] 2017-10-23 15:28
@tricoder42 I tried the example project and it works.
Output of `npm list` : 

[npmlist.json.zip](https://github.com/lingui/js-lingui/files/1407731/npmlist.json.zip)

**Comment by shye0000** [comment] 2017-10-23 15:39
@tricoder42 I found the problem! I use 'babel-plugin-resolver' in my project (https://www.npmjs.com/package/babel-plugin-resolver)
`lingui extract` works if I remove it from babel plugins.

**Comment by tricoder42** [comment] 2017-10-23 15:40
Wow, alright, I'll take a look why it causes problem with lingui. Thank you very much!

**Comment by shye0000** [comment] 2017-10-23 15:47
@tricoder42 You are welcome! I really like js-lingui and would like to use it with my real projects. Hope you can find the solution soon, thanks a lot.

**Comment by tricoder42** [comment] 2017-10-23 18:39
@shye0000 Found the root cause. It should be fixed now. Please update the root packages you use:

 - babel-plugin-lingui-extract-messages@1.1.5
 - babel-plugin-lingui-transform-react@1.1.2
 - babel-preset-lingui-react@1.0.9
 - lingui-cli@1.3.8
 - lingui-i18n@1.3.2
 - lingui-react@1.3.3

**Closed** 2017-10-23 18:40 UTC
Labels: bug, package: lingui-cli

**Comment by shye0000** [comment] 2017-10-24 08:06
@tricoder42 Thank you very much, works like a charm!

**Comment by Bhim3807** [comment] 2020-04-22 08:52
@tricoder42  same issue with my project also unable to extract messages after running lingui extract
