### ISSUE TITLE
Is there a way to prefix id with a file path

### ISSUE THREAD

**Issue by lolenko** [lingui/js-lingui#624] opened 2020-03-27 10:13 UTC
I'll try to explain
it'll be really cool if you are able to provide such option when output key is path.to.file:id 
so in code it's just \<Trans id="hello"\>Hello\</Trans\>  as it is now
but messages.js contains keys what look like path.to.file:id 

it's inconvenient now to come up with an exclusive key every time

**Comment by tricoder42** [comment] 2020-04-11 17:11
Personally I prefer original message to be used as a key. I understand that some people make their own IDs and they usually try to make them as helpful as possible for translators, eg: `Login Page \ Main sign up button`.

Anyway, this seems to be a duplicate of #402.

**Closed by tricoder42** 2020-04-11 17:11 UTC
Labels: triage: duplicate
