### ISSUE TITLE
In some cases function t() macros message is not extracted when ID is present

### ISSUE THREAD

**Issue by rafalp** [lingui/js-lingui#866] opened 2020-11-14 17:02 UTC
**Describe the bug**
When `t()` macro is used with object defining id and message, message part is skipped when extracted default locale. 

**To Reproduce**

```
import { t } from "@lingui/macro"

export default function App() {
   return <p>{t({id: "hello_world", message: "Hello world!"})}</p>
}
```

Run lingui extract. PO file will be generated discarding `message` part:

```
msgid "hello_world"
msgstr "hello_world"
```

**Expected behavior**
PO file generated by `lingui extract` should contain following entry for default locale:

```
msgid "hello_world"
msgstr "Hello world!"
```

**Additional context**

I am using lingui version 3.2.1 with CRA 4.

This issue only occurs for `t()` from what I've seen so far. I am also using `<Trans id="...">...</Trans>` macro and that one is extracted correctly.

**Comment by rafalp** [comment] 2020-11-14 18:21
I am at loss here. I've inspected my project closer and realized that `lingui extract` actually extracts message for some of macros, while it skips the others.

**Comment by rafalp** [comment] 2020-11-14 18:28
I've found that this is the case when `message` value is formatted string:

```
// Works
export default function App() {
  return <p>{t({id: "hello_world", message: "Hello world!"})}</p>
}
```

This won't work:

```
// Works
export default function App() {
  return <p>{t({id: "hello_world", message: `Hello world!`})}</p>
}
```

**Comment by tricoder42** [comment] 2020-11-14 18:40
Hey @rafalp, this is known issue already fixed in #862. It wasn't released yet though. Meanwhile, please check possible workarounds https://github.com/lingui/js-lingui/issues/861#issuecomment-726641318

**Comment by tricoder42** [comment] 2020-11-14 18:40
Duplicate of #861

**Closed by tricoder42** 2020-11-14 18:40 UTC

**Comment by rafalp** [comment] 2020-11-14 18:51
Oooh, I've missed that comment! Thank you!
